import type { PortalSnapshot } from "./types";

export const consultantSnapshot: PortalSnapshot = {
  profile: {
    id: "demo-consultant",
    email: "roland.schneider@example.de",
    fullName: "Roland Schneider",
    businessName: "HS Consulting",
    country: "Germany",
    phone: "+49 000 000000",
    role: "consultant",
  },
  assignment: {
    id: "assignment-planning-cluster-lead",
    title: "Planning Cluster Lead",
    programme: "SAP S/4HANA Business Transformation Programme",
    customer: "SNECI SAS",
    endCustomer: "Heinz-Glas GmbH & Co. KGaA",
    location: "Kleintettau, Bavaria, Germany",
    startDate: "3 August 2026",
    expectedEnd: "Approximately March 2027, subject to customer requirements",
    onsiteExpectation: "Approximately four to five days per week",
    dailyRate: "€500 per day",
    trialPeriod: "One month",
    notice:
      "Thirty calendar days, subject to customer-led termination rights",
    accommodation: "Arranged and paid directly by the Customer",
    travel:
      "Reasonable agreed fuel and vehicle travel costs reimbursed by DeepBridge against receipts and journey records",
    commercialContact: {
      name: "Yon Wallace",
      role: "DeepBridge commercial contact",
      email: "yon@deepbridgeadvisory.co.uk",
    },
  },
  documents: [
    {
      id: "framework",
      title: "Professional Consulting Services Framework Agreement",
      description:
        "The overarching terms for your independent consulting engagement with DeepBridge.",
      category: "signature",
      status: "ready_to_sign",
      version: "1.0",
      updatedAt: "24 July 2026",
    },
    {
      id: "sow",
      title: "Statement of Work — Planning Cluster Lead",
      description:
        "Assignment-specific scope, commercial terms, location and expected duration.",
      category: "signature",
      status: "awaiting_deepbridge",
      version: "1.0",
      updatedAt: "25 July 2026",
    },
    {
      id: "charter",
      title: "Professional Consultant Charter Acknowledgement",
      description:
        "Professional standards and working principles for DeepBridge consultants.",
      category: "signature",
      status: "completed",
      version: "1.0",
      updatedAt: "23 July 2026",
      completedAt: "23 July 2026",
      certificateAvailable: true,
    },
    {
      id: "commercial-policy",
      title: "Commercial Administration Policy",
      description: "Timesheets, purchase orders, invoicing and administration.",
      category: "acknowledgement",
      status: "read",
      version: "1.2",
      updatedAt: "18 July 2026",
    },
    {
      id: "travel-policy",
      title: "Travel, Expenses and Invoicing Policy",
      description:
        "Evidence, approval and submission requirements for reimbursable costs.",
      category: "acknowledgement",
      status: "not_reviewed",
      version: "1.1",
      updatedAt: "18 July 2026",
    },
    {
      id: "security-policy",
      title: "Information Security and AI Policy",
      description:
        "Rules for customer information, systems, devices and AI-assisted tools.",
      category: "acknowledgement",
      status: "not_reviewed",
      version: "1.0",
      updatedAt: "20 July 2026",
    },
    {
      id: "customer-requirements",
      title: "Customer-Specific Requirements",
      description:
        "Practical controls and working requirements for the current assignment.",
      category: "acknowledgement",
      status: "not_reviewed",
      version: "1.0",
      updatedAt: "22 July 2026",
    },
    {
      id: "deliverables",
      title: "Deliverables and Acceptance Criteria",
      description: "Expected outputs, review points and acceptance approach.",
      category: "acknowledgement",
      status: "not_reviewed",
      version: "1.0",
      updatedAt: "22 July 2026",
    },
    {
      id: "welcome",
      title: "Welcome Letter",
      description:
        "A short introduction to DeepBridge and your onboarding contacts.",
      category: "information",
      status: "not_reviewed",
      version: "1.0",
      updatedAt: "21 July 2026",
    },
    {
      id: "mobilisation",
      title: "Project Mobilisation Pack",
      description: "First-day information and practical mobilisation guidance.",
      category: "information",
      status: "not_reviewed",
      version: "1.0",
      updatedAt: "25 July 2026",
    },
  ],
  compliance: [
    {
      id: "business-registration",
      title: "German business registration",
      description: "Current registration evidence for your consulting business.",
      status: "accepted",
      required: true,
      uploadedAt: "22 July 2026",
      administratorNote: "Verified by DeepBridge.",
      submissionId: "demo-registration",
      scanStatus: "clean",
    },
    {
      id: "vat",
      title: "VAT confirmation",
      description: "Your current German VAT registration confirmation.",
      status: "under_review",
      required: true,
      uploadedAt: "24 July 2026",
      submissionId: "demo-vat",
      scanStatus: "clean",
    },
    {
      id: "tax",
      title: "Tax information",
      description: "Tax information required for contracting and invoicing.",
      status: "missing",
      required: true,
    },
    {
      id: "professional-indemnity",
      title: "Professional indemnity certificate",
      description: "Current policy schedule or certificate of insurance.",
      status: "uploaded",
      required: true,
      uploadedAt: "25 July 2026",
      expiryDate: "30 June 2027",
      submissionId: "demo-pi",
      scanStatus: "clean",
    },
    {
      id: "public-liability",
      title: "Public liability certificate",
      description: "Current public liability insurance evidence.",
      status: "missing",
      required: true,
    },
    {
      id: "identity",
      title: "Passport or national identity document",
      description:
        "A clear copy used only for identity and compliance verification.",
      status: "under_review",
      required: true,
      uploadedAt: "24 July 2026",
      submissionId: "demo-id",
      scanStatus: "clean",
    },
    {
      id: "bank",
      title: "Bank confirmation",
      description:
        "Account ownership evidence. You may redact unrelated transactions.",
      status: "missing",
      required: true,
    },
    {
      id: "a1",
      title: "A1 certificate",
      description: "Required where applicable to the cross-border assignment.",
      status: "missing",
      required: false,
    },
    {
      id: "cv",
      title: "Curriculum vitae",
      description: "Your current professional profile.",
      status: "accepted",
      required: true,
      uploadedAt: "20 July 2026",
      submissionId: "demo-cv",
      scanStatus: "clean",
    },
    {
      id: "certifications",
      title: "Professional certifications",
      description: "Relevant professional or technical certifications.",
      status: "missing",
      required: false,
    },
  ],
  tasks: [
    {
      id: "profile",
      title: "Profile completed",
      description: "Contact and business details supplied.",
      complete: true,
      internal: false,
    },
    {
      id: "agreement",
      title: "Framework Agreement signed",
      description: "Google Workspace signature request sent to your email.",
      complete: false,
      internal: false,
    },
    {
      id: "sow",
      title: "Statement of Work signed",
      description: "Awaiting DeepBridge countersignature.",
      complete: false,
      internal: false,
    },
    {
      id: "charter",
      title: "Charter acknowledged",
      description: "Completed.",
      complete: true,
      internal: false,
    },
    {
      id: "insurance",
      title: "Insurance uploaded",
      description: "One insurance document remains outstanding.",
      complete: false,
      internal: false,
    },
    {
      id: "registration",
      title: "Business registration uploaded",
      description: "Accepted by DeepBridge.",
      complete: true,
      internal: false,
    },
    {
      id: "tax",
      title: "Tax and VAT details supplied",
      description: "Tax information remains outstanding.",
      complete: false,
      internal: false,
    },
    {
      id: "bank",
      title: "Banking details supplied",
      description: "Secure bank confirmation is required.",
      complete: false,
      internal: false,
    },
    {
      id: "identity",
      title: "Identity document supplied",
      description: "Under review.",
      complete: true,
      internal: false,
    },
    {
      id: "systems",
      title: "Customer systems ready",
      description: "DeepBridge will confirm when access is ready.",
      complete: false,
      internal: false,
    },
    {
      id: "first-day",
      title: "First day confirmed",
      description: "Final arrival details will be issued before mobilisation.",
      complete: false,
      internal: false,
    },
  ],
  audit: [
    {
      id: "audit-1",
      action: "File accepted",
      actor: "DeepBridge Administrator",
      object: "German business registration",
      createdAt: "25 Jul 2026, 14:32",
    },
    {
      id: "audit-2",
      action: "Signature completed",
      actor: "Roland Schneider",
      object: "Professional Consultant Charter Acknowledgement v1.0",
      createdAt: "23 Jul 2026, 10:18",
    },
    {
      id: "audit-3",
      action: "Invitation accepted",
      actor: "Roland Schneider",
      object: "Portal access",
      createdAt: "21 Jul 2026, 09:04",
    },
  ],
};

export const adminSnapshot: PortalSnapshot = {
  ...consultantSnapshot,
  profile: {
    id: "demo-admin",
    email: "admin@deepbridgeadvisory.co.uk",
    fullName: "DeepBridge Administrator",
    businessName: "DustDeep Ltd",
    country: "United Kingdom",
    phone: "",
    role: "admin",
  },
  tasks: [
    ...consultantSnapshot.tasks,
    {
      id: "references-internal",
      title: "References verified",
      description: "Internal DeepBridge check.",
      complete: true,
      internal: true,
    },
    {
      id: "customer-approval-internal",
      title: "Customer approval recorded",
      description: "Internal DeepBridge check.",
      complete: true,
      internal: true,
    },
    {
      id: "documents-internal",
      title: "Identity and registration verified",
      description: "Internal DeepBridge check.",
      complete: false,
      internal: true,
    },
  ],
};
